### ISSUE TITLE
图片压缩报错

### ISSUE THREAD

**Issue by DarkerSU** [1071942338/WebpackStudyNotes#1]
使用你的图片压缩报如下错误，有解决方案吗？

ERROR in ./src/222.jpg
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-pngquant'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (G:\WebpackStudyNotes\17-webpack 压缩图片\demo17\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.module.exports (G:\WebpackStudyNotes\17-webpack 压缩图片\demo17\node_modules\image-webpack-loader\index.js:72:20)
 @ ./src/index.js 2:0-29 18:18-22

**Comment by hao-kuai** [comment]
抱歉，才看到你的问题！你的问题解决了吗？没有解决的话最好能把你的代码提出来，我能够复现你的问题才能解决
